var builder = WebApplication.CreateBuilder(args);

builder.Services.AddSingleton<DataContext>();
builder.Services.AddTransient<IDataRepo, DataRepo>();
var app = builder.Build();

app.MapGet("/", (IDataRepo repo)=> repo.GetAll());
app.MapGet("/{id}", (int id, IDataRepo repo)=> repo.Get(id));
app.MapPost("/", (Data postedValue, IDataRepo repo)=> { repo.AddData(postedValue); });




// app.Urls.Add("http://localhost:5000");
// app.Urls.Add("http://localhost:6000");

//Run method does not need to mention the URL, if not provided, will use the random port no generated by the .NET CORE. 
app.Run("http://localhost:1234");
